######################################################################
# Automatically generated by qmake (2.01a) Sun May 4 10:37:53 2014
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += player.h
SOURCES += main.cpp player.cpp
